### ISSUE TITLE
Couldn't load dependencies of asset: scene/example.scene

### ISSUE THREAD

**Issue by oZBo** [kotcrab/VisEditor#110] opened 2015-12-23 13:23 UTC
Hi all! Doing all like in the wik, but in the runtime of the desktop app i got an error:
"Caused by: java.lang.NumberFormatException: For input string: "size"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.kotcrab.vis.runtime.scene.IntMapJsonSerializer.read(IntMapJsonSerializer.java:45)
	at com.kotcrab.vis.runtime.scene.IntMapJsonSerializer.read(IntMapJsonSerializer.java:27)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:867)
	at com.badlogic.gdx.utils.Json.readFields(Json.java:780)
	... 11 more"
What i'm doing wrong? 

Thanks in advance!

**Comment by intrigus** [comment] 2015-12-23 13:28
Could you please post the content of 'scene/example.scene' ? Please use pastebin.com or another paste-service for this.

**Comment by oZBo** [comment] 2015-12-23 13:57
{  
   viewport:{  
      class:SceneViewport,
      value:STRETCH
   },
   width:8,
   height:4.8,
   pixelsPerUnit:100,
   physicsSettings:{  

   },
   groupIds:{  
      size:0,
      entries:[  

      ]
   },
   layers:[  
      {  
         cordsSystem:{  
            class:LayerCordsSystem,
            value:WORLD
         },
         name:Background
      }
   ],
   entities:[  
      {  
         components:[  
            {  
               class:AssetReference,
               asset:{  
                  class:TextureRegionAsset,
                  relativePath:gfx/background.png
               }
            },
            {  
               class:Layer
            },
            {  
               class:ProtoVisSprite,
               width:8,
               height:4.8
            },
            {  
               class:Transform
            },
            {  
               class:Origin,
               originX:4,
               originY:2.4
            },
            {  
               class:Tint
            },
            {  
               class:Renderable
            }
         ]
      },
      {  
         components:[  
            {  
               class:AssetReference,
               asset:{  
                  class:TextureRegionAsset,
                  relativePath:gfx/groundDirt.png
               }
            },
            {  
               class:Layer
            },
            {  
               class:ProtoVisSprite,
               width:8.08,
               height:0.71
            },
            {  
               class:Transform,
               x:-0.112113714,
               y:0.010192037,
               scaleX:0.97
            },
            {  
               class:Origin,
               originX:4.04,
               originY:0.355
            },
            {  
               class:Tint
            },
            {  
               class:Renderable
            }
         ]
      },
      {  
         components:[  
            {  
               class:AssetReference,
               asset:{  
                  class:TextureRegionAsset,
                  relativePath:gfx/Planes/planeGreen1.png
               }
            },
            {  
               class:Layer
            },
            {  
               class:ProtoVisSprite,
               width:0.88,
               height:0.73
            },
            {  
               class:Transform,
               x:1.0201378,
               y:2.4482567
            },
            {  
               class:Origin,
               originX:0.44,
               originY:0.365
            },
            {  
               class:Tint
            },
            {  
               class:Renderable
            }
         ]
      }
   ]
}

Sorry if formatting looks bad..

**Comment by kotcrab** [comment] 2015-12-23 14:24
Please use pastebin or gist in the future.

Looks like you are using wrong runtime version with editor version. If you are using editor 0.3.0 you need runtime 0.3.0. For editor 0.3.1-SNAPSHOT you need runtime 0.3.1-SNAPSHOT. Also don't forget you need to reexport your scenes if you change editor versions.

Now that said this is probably error with example project, I'll check that.

**Comment by oZBo** [comment] 2015-12-23 14:31
Changing runtime versrion to 0.3.0 resolved the issue! Thanks you a lot!
I was using the import mechanism provided by libGDX project creator and it set gradle runtime import to 0.2.1 version.

**Comment by oZBo** [comment] 2015-12-23 14:33
Egh.. I don't if it correct place to post it, but when i press a lot of times CTRL+Z editor crashes

**Comment by kotcrab** [comment] 2015-12-23 21:00
> I was using the import mechanism provided by libGDX project creator and it set gradle runtime import to 0.2.1 version. 

Then your project creator is out of date, also note that external extension versions in gdx-setup may not be up to date with current release versions.

>Egh.. I don't if it correct place to post it, but when i press a lot of times CTRL+Z editor crashes

Probably already fixed in #106. Next time please create separate issue and include steps to reproduce the problem and provide exception stack trace (found in crash files or logs, see https://github.com/kotcrab/VisEditor/wiki/Locating-Log-Files).

**Closed by kotcrab** 2015-12-23 21:00 UTC
