### ISSUE TITLE
NumberSelector

### ISSUE THREAD

**Issue by LoekSangers** [kotcrab/VisEditor#7] opened 2015-05-17 20:20 UTC
There are a few errors with the current NumberSelector, or I'm using it wrong =). The main problem is that when you have a minimum value greater then 1, you can not remove the complete value and fill in the wanted value, e.g. if the minimum value is 5 and i want to pick a value of 10, removing the 5 and then typing 1 results in a 5 because 1 is not a valid input. 

Another problem i came across is that on my android phone if I pick a number with a virtual keyboard that number gets repeated as if the timer for the up/down button gets fired for the number I picked.

Also is there any support for a form validator with a NumberSelector in it?

**Comment by kotcrab** [comment] 2015-05-18 17:18
Confirmed first input issue, will look into that.

When the timers fires it can only increment or decrement current value, it can't repeat number you pressed so I don't think that's it. [This is timer task] (https://github.com/kotcrab/VisEditor/blob/master/UI/src/com/kotcrab/vis/ui/widget/NumberSelector.java#L309-L319). There was bug in libGDX TextField that was causing repeating last entered char if field lost focus before getting touchUp event, it was fixed in VisUI 0.7.4. Maybe that was that?

NumberSelector supports setting min and max value, I could add method to add custom validators but is there really anything else you would like to validate?

**Comment by LoekSangers** [comment] 2015-05-18 18:21
The validation was to force the NumberSelector to not be empty, but I guess the min and max values also guarantee this.

It might be the libGDX TextField that is causing the repeating input, but with libGDX 1.6.0 and VisUI 0.7.7-SNAPSHOT it isn't working for me. I will test a bit to see if I can find what exactly causes the problem.

**Comment by kotcrab** [comment] 2015-05-18 18:42
The new behavior is to restore last valid entered value when field loses focus. This allows to enters all values while text field has focus but when focus is lost the last valid value will be restored (or the minimum set value if field was empty).

You can't force selector to be not empty, that would cause the same issue as you described in your first message.

You should try if that repeat bug occurs in `VisValidableTextField`, then we will know if it is related to number selector or the text filed itself.

**Comment by LoekSangers** [comment] 2015-05-18 18:52
I get the same problem with VisValidatableTextField, so it is the textfield itself.

And i don't see any changes with the NumberSelector, but i don't know if I should see that already or if that takes some time =).

**Comment by kotcrab** [comment] 2015-05-18 19:02
Okay, now if you could test it in `VisTextField` and standard libGDX `TextField`. You can pass `VisUI.getSkin()` to `TextField` constructor, they are compatible.

Changing commit is here b60eca3d75c78e2b295b9a39b47bd10a1854be9b but snapshots takes some time to update (typically 10 mins), also don't forget to refresh Gradle caches / dependencies.

**Comment by LoekSangers** [comment] 2015-05-18 19:08
The virtual keyboard works without repeating charactersin the the libGDX TextField, but the VisTextField has the repeating characters.

**Comment by kotcrab** [comment] 2015-05-18 19:32
Thanks, that's helpful, I can reproduce it now. This issue is caused by key repeat task in `VisTextField` which works in different way than in `TextField`, I'm looking into it.

**Comment by LoekSangers** [comment] 2015-05-18 19:33
Thanks for looking into it and for making VisUI =).

**Closed** 2015-05-18 20:07 UTC
